// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/PacktPublishing/Building-Microservices-with-Go-Second-Edition/product-api/9_docs/client-sdk/models"
)

// DeleteReader is a Reader for the Delete structure.
type DeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCreated creates a DeleteCreated with default headers values
func NewDeleteCreated() *DeleteCreated {
	return &DeleteCreated{}
}

/*DeleteCreated handles this case with default header values.

No content is returned by this API endpoint
*/
type DeleteCreated struct {
}

func (o *DeleteCreated) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteCreated ", 201)
}

func (o *DeleteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNotFound creates a DeleteNotFound with default headers values
func NewDeleteNotFound() *DeleteNotFound {
	return &DeleteNotFound{}
}

/*DeleteNotFound handles this case with default header values.

Generic error message returned as a string
*/
type DeleteNotFound struct {
	Payload *models.GenericError
}

func (o *DeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteNotFound  %+v", 404, o.Payload)
}

func (o *DeleteNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotImplemented creates a DeleteNotImplemented with default headers values
func NewDeleteNotImplemented() *DeleteNotImplemented {
	return &DeleteNotImplemented{}
}

/*DeleteNotImplemented handles this case with default header values.

Generic error message returned as a string
*/
type DeleteNotImplemented struct {
	Payload *models.GenericError
}

func (o *DeleteNotImplemented) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
