// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Enumerations
type Diet int32

const (
	Diet_VEGAN       Diet = 0
	Diet_VEGITARIAN  Diet = 1
	Diet_PESCATARIAN Diet = 2
	Diet_GLUTEN_FREE Diet = 3
	Diet_DAIRY_FREE  Diet = 4
)

var Diet_name = map[int32]string{
	0: "VEGAN",
	1: "VEGITARIAN",
	2: "PESCATARIAN",
	3: "GLUTEN_FREE",
	4: "DAIRY_FREE",
}

var Diet_value = map[string]int32{
	"VEGAN":       0,
	"VEGITARIAN":  1,
	"PESCATARIAN": 2,
	"GLUTEN_FREE": 3,
	"DAIRY_FREE":  4,
}

func (x Diet) String() string {
	return proto.EnumName(Diet_name, int32(x))
}

func (Diet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

type Recipie_Available int32

const (
	Recipie_ALL_DAY Recipie_Available = 0
	Recipie_LUNCH   Recipie_Available = 1
	Recipie_BRUNCH  Recipie_Available = 1
	Recipie_DINNER  Recipie_Available = 2
)

var Recipie_Available_name = map[int32]string{
	0: "ALL_DAY",
	1: "LUNCH",
	// Duplicate value: 1: "BRUNCH",
	2: "DINNER",
}

var Recipie_Available_value = map[string]int32{
	"ALL_DAY": 0,
	"LUNCH":   1,
	"BRUNCH":  1,
	"DINNER":  2,
}

func (x Recipie_Available) String() string {
	return proto.EnumName(Recipie_Available_name, int32(x))
}

func (Recipie_Available) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4, 0}
}

// Simple message with scalar types
type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Sku                  string   `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

// Embedding messages
// Messages can be used as types in other messages, they can either use
// external messages or embed their own messages.
type Order struct {
	Product              *Product        `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Customer             *Order_Customer `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Order) GetCustomer() *Order_Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type Order_Customer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_Customer) Reset()         { *m = Order_Customer{} }
func (m *Order_Customer) String() string { return proto.CompactTextString(m) }
func (*Order_Customer) ProtoMessage()    {}
func (*Order_Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1, 0}
}

func (m *Order_Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_Customer.Unmarshal(m, b)
}
func (m *Order_Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_Customer.Marshal(b, m, deterministic)
}
func (m *Order_Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_Customer.Merge(m, src)
}
func (m *Order_Customer) XXX_Size() int {
	return xxx_messageInfo_Order_Customer.Size(m)
}
func (m *Order_Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Order_Customer proto.InternalMessageInfo

func (m *Order_Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order_Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// Lists
// Messages can contain lists of scalar types or messages using the repeated keyword
type ServerOrders struct {
	Server               *ServerOrders_Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Order                []*Order             `protobuf:"bytes,2,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ServerOrders) Reset()         { *m = ServerOrders{} }
func (m *ServerOrders) String() string { return proto.CompactTextString(m) }
func (*ServerOrders) ProtoMessage()    {}
func (*ServerOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *ServerOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerOrders.Unmarshal(m, b)
}
func (m *ServerOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerOrders.Marshal(b, m, deterministic)
}
func (m *ServerOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerOrders.Merge(m, src)
}
func (m *ServerOrders) XXX_Size() int {
	return xxx_messageInfo_ServerOrders.Size(m)
}
func (m *ServerOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerOrders.DiscardUnknown(m)
}

var xxx_messageInfo_ServerOrders proto.InternalMessageInfo

func (m *ServerOrders) GetServer() *ServerOrders_Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ServerOrders) GetOrder() []*Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ServerOrders_Server struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerOrders_Server) Reset()         { *m = ServerOrders_Server{} }
func (m *ServerOrders_Server) String() string { return proto.CompactTextString(m) }
func (*ServerOrders_Server) ProtoMessage()    {}
func (*ServerOrders_Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2, 0}
}

func (m *ServerOrders_Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerOrders_Server.Unmarshal(m, b)
}
func (m *ServerOrders_Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerOrders_Server.Marshal(b, m, deterministic)
}
func (m *ServerOrders_Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerOrders_Server.Merge(m, src)
}
func (m *ServerOrders_Server) XXX_Size() int {
	return xxx_messageInfo_ServerOrders_Server.Size(m)
}
func (m *ServerOrders_Server) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerOrders_Server.DiscardUnknown(m)
}

var xxx_messageInfo_ServerOrders_Server proto.InternalMessageInfo

func (m *ServerOrders_Server) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Maps
// messages can contain maps map<key, value>
type RestaurantOrders struct {
	// maps can contain scalar types as values
	RestaurantOrderCount map[string]float64 `protobuf:"bytes,1,rep,name=restaurant_order_count,json=restaurantOrderCount,proto3" json:"restaurant_order_count,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	// maps can contain messages as values
	RestaurantServerOrders map[string]*ServerOrders `protobuf:"bytes,2,rep,name=restaurant_server_orders,json=restaurantServerOrders,proto3" json:"restaurant_server_orders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *RestaurantOrders) Reset()         { *m = RestaurantOrders{} }
func (m *RestaurantOrders) String() string { return proto.CompactTextString(m) }
func (*RestaurantOrders) ProtoMessage()    {}
func (*RestaurantOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *RestaurantOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantOrders.Unmarshal(m, b)
}
func (m *RestaurantOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantOrders.Marshal(b, m, deterministic)
}
func (m *RestaurantOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantOrders.Merge(m, src)
}
func (m *RestaurantOrders) XXX_Size() int {
	return xxx_messageInfo_RestaurantOrders.Size(m)
}
func (m *RestaurantOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantOrders.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantOrders proto.InternalMessageInfo

func (m *RestaurantOrders) GetRestaurantOrderCount() map[string]float64 {
	if m != nil {
		return m.RestaurantOrderCount
	}
	return nil
}

func (m *RestaurantOrders) GetRestaurantServerOrders() map[string]*ServerOrders {
	if m != nil {
		return m.RestaurantServerOrders
	}
	return nil
}

type Recipie struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Suitability          []Diet            `protobuf:"varint,2,rep,packed,name=suitability,proto3,enum=example.Diet" json:"suitability,omitempty"`
	Available            Recipie_Available `protobuf:"varint,3,opt,name=available,proto3,enum=example.Recipie_Available" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Recipie) Reset()         { *m = Recipie{} }
func (m *Recipie) String() string { return proto.CompactTextString(m) }
func (*Recipie) ProtoMessage()    {}
func (*Recipie) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{4}
}

func (m *Recipie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipie.Unmarshal(m, b)
}
func (m *Recipie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipie.Marshal(b, m, deterministic)
}
func (m *Recipie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipie.Merge(m, src)
}
func (m *Recipie) XXX_Size() int {
	return xxx_messageInfo_Recipie.Size(m)
}
func (m *Recipie) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipie.DiscardUnknown(m)
}

var xxx_messageInfo_Recipie proto.InternalMessageInfo

func (m *Recipie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipie) GetSuitability() []Diet {
	if m != nil {
		return m.Suitability
	}
	return nil
}

func (m *Recipie) GetAvailable() Recipie_Available {
	if m != nil {
		return m.Available
	}
	return Recipie_ALL_DAY
}

type ErrorMessage struct {
	Error                *status.Status       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{5}
}

func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (m *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(m, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ErrorMessage) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Ingredients struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NutricionalInfo      []*any.Any `protobuf:"bytes,2,rep,name=nutricional_info,json=nutricionalInfo,proto3" json:"nutricional_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Ingredients) Reset()         { *m = Ingredients{} }
func (m *Ingredients) String() string { return proto.CompactTextString(m) }
func (*Ingredients) ProtoMessage()    {}
func (*Ingredients) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{6}
}

func (m *Ingredients) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredients.Unmarshal(m, b)
}
func (m *Ingredients) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredients.Marshal(b, m, deterministic)
}
func (m *Ingredients) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredients.Merge(m, src)
}
func (m *Ingredients) XXX_Size() int {
	return xxx_messageInfo_Ingredients.Size(m)
}
func (m *Ingredients) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredients.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredients proto.InternalMessageInfo

func (m *Ingredients) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredients) GetNutricionalInfo() []*any.Any {
	if m != nil {
		return m.NutricionalInfo
	}
	return nil
}

// Define messages which can be of different fixed types
type SubscribeOrderResponse struct {
	// message will contain one of the two types
	// setting one of these types automatically clears all other members
	// only the last field you set will have a value
	//
	// Types that are valid to be assigned to Message:
	//	*SubscribeOrderResponse_Order
	//	*SubscribeOrderResponse_Error
	Message              isSubscribeOrderResponse_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SubscribeOrderResponse) Reset()         { *m = SubscribeOrderResponse{} }
func (m *SubscribeOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeOrderResponse) ProtoMessage()    {}
func (*SubscribeOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{7}
}

func (m *SubscribeOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeOrderResponse.Unmarshal(m, b)
}
func (m *SubscribeOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeOrderResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeOrderResponse.Merge(m, src)
}
func (m *SubscribeOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeOrderResponse.Size(m)
}
func (m *SubscribeOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeOrderResponse proto.InternalMessageInfo

type isSubscribeOrderResponse_Message interface {
	isSubscribeOrderResponse_Message()
}

type SubscribeOrderResponse_Order struct {
	Order *Order `protobuf:"bytes,1,opt,name=order,proto3,oneof"`
}

type SubscribeOrderResponse_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SubscribeOrderResponse_Order) isSubscribeOrderResponse_Message() {}

func (*SubscribeOrderResponse_Error) isSubscribeOrderResponse_Message() {}

func (m *SubscribeOrderResponse) GetMessage() isSubscribeOrderResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SubscribeOrderResponse) GetOrder() *Order {
	if x, ok := m.GetMessage().(*SubscribeOrderResponse_Order); ok {
		return x.Order
	}
	return nil
}

func (m *SubscribeOrderResponse) GetError() *status.Status {
	if x, ok := m.GetMessage().(*SubscribeOrderResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubscribeOrderResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubscribeOrderResponse_Order)(nil),
		(*SubscribeOrderResponse_Error)(nil),
	}
}

func init() {
	proto.RegisterEnum("example.Diet", Diet_name, Diet_value)
	proto.RegisterEnum("example.Recipie_Available", Recipie_Available_name, Recipie_Available_value)
	proto.RegisterType((*Product)(nil), "example.Product")
	proto.RegisterType((*Order)(nil), "example.Order")
	proto.RegisterType((*Order_Customer)(nil), "example.Order.Customer")
	proto.RegisterType((*ServerOrders)(nil), "example.ServerOrders")
	proto.RegisterType((*ServerOrders_Server)(nil), "example.ServerOrders.Server")
	proto.RegisterType((*RestaurantOrders)(nil), "example.RestaurantOrders")
	proto.RegisterMapType((map[string]float64)(nil), "example.RestaurantOrders.RestaurantOrderCountEntry")
	proto.RegisterMapType((map[string]*ServerOrders)(nil), "example.RestaurantOrders.RestaurantServerOrdersEntry")
	proto.RegisterType((*Recipie)(nil), "example.Recipie")
	proto.RegisterType((*ErrorMessage)(nil), "example.ErrorMessage")
	proto.RegisterType((*Ingredients)(nil), "example.Ingredients")
	proto.RegisterType((*SubscribeOrderResponse)(nil), "example.SubscribeOrderResponse")
}

func init() {
	proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6)
}

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 794 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xef, 0x6e, 0xdb, 0x36,
	0x10, 0x0f, 0x65, 0x3b, 0xae, 0x4f, 0xad, 0x23, 0x10, 0x59, 0xeb, 0x6a, 0x05, 0x6a, 0x08, 0xc3,
	0x60, 0x64, 0x80, 0x32, 0x38, 0x1d, 0x50, 0x0c, 0x18, 0x0a, 0x35, 0xd1, 0x52, 0x03, 0x99, 0x57,
	0xd0, 0x6e, 0x81, 0x7e, 0xf2, 0x64, 0x99, 0x71, 0x88, 0xda, 0x92, 0x40, 0x4a, 0xd9, 0xfc, 0x06,
	0x7b, 0x85, 0x7d, 0xd9, 0x97, 0x3d, 0xcd, 0xde, 0x6a, 0xe0, 0x1f, 0x29, 0xaa, 0xa7, 0x66, 0xfb,
	0xc6, 0xbb, 0xfb, 0xf1, 0x7e, 0x77, 0x3f, 0xf2, 0x0e, 0x1e, 0xd1, 0xdf, 0xa2, 0x6d, 0xb6, 0xa1,
	0x7e, 0xc6, 0xd3, 0x3c, 0xc5, 0x5d, 0x63, 0xba, 0x4f, 0xd6, 0x69, 0xba, 0xde, 0xd0, 0x53, 0x9e,
	0xc5, 0xa7, 0x22, 0x8f, 0xf2, 0x42, 0x68, 0x84, 0xfb, 0xdc, 0x04, 0x94, 0xb5, 0x2c, 0xae, 0x4f,
	0x73, 0xb6, 0xa5, 0x22, 0x8f, 0xb6, 0x99, 0x01, 0x3c, 0xdd, 0x07, 0x44, 0xc9, 0x4e, 0x87, 0xbc,
	0x5f, 0xa1, 0xfb, 0x96, 0xa7, 0xab, 0x22, 0xce, 0x71, 0x1f, 0x2c, 0xb6, 0x1a, 0xa0, 0x21, 0x1a,
	0x75, 0x88, 0xc5, 0x56, 0x18, 0x43, 0x3b, 0x89, 0xb6, 0x74, 0x60, 0x0d, 0xd1, 0xa8, 0x47, 0xd4,
	0x19, 0x0f, 0xc1, 0x5e, 0x51, 0x11, 0x73, 0x96, 0xe5, 0x2c, 0x4d, 0x06, 0x2d, 0x15, 0xaa, 0xbb,
	0xf0, 0x31, 0x74, 0x32, 0xce, 0x62, 0x3a, 0x68, 0x0f, 0xd1, 0x08, 0x11, 0x6d, 0x60, 0x07, 0x5a,
	0xe2, 0x63, 0x31, 0xe8, 0x28, 0xbc, 0x3c, 0x7a, 0x7f, 0x22, 0xe8, 0xfc, 0xcc, 0x57, 0x94, 0xe3,
	0x13, 0xe8, 0x66, 0xba, 0x04, 0x45, 0x6e, 0x8f, 0x1d, 0xbf, 0x54, 0xc0, 0x94, 0x46, 0x4a, 0x00,
	0x3e, 0x83, 0x07, 0x71, 0x21, 0xf2, 0x74, 0x4b, 0xb9, 0xaa, 0xcb, 0x1e, 0x3f, 0xa9, 0xc0, 0x2a,
	0x9b, 0x7f, 0x6e, 0xc2, 0xa4, 0x02, 0xba, 0x2f, 0xe0, 0x41, 0xe9, 0xad, 0x9a, 0x42, 0xb5, 0xa6,
	0x64, 0xc9, 0x37, 0x69, 0x52, 0x76, 0xaa, 0x0d, 0xef, 0x77, 0x04, 0x0f, 0x67, 0x94, 0xdf, 0x52,
	0xae, 0x12, 0x0b, 0xfc, 0x02, 0x0e, 0x85, 0xb2, 0x4d, 0x99, 0xcf, 0x2a, 0xe6, 0x3a, 0xcc, 0x18,
	0xc4, 0x60, 0xf1, 0x57, 0xd0, 0x49, 0x65, 0x60, 0x60, 0x0d, 0x5b, 0x23, 0x7b, 0xdc, 0xff, 0xb4,
	0x5c, 0xa2, 0x83, 0xee, 0x33, 0x38, 0xd4, 0xf7, 0x9a, 0x0a, 0xf4, 0xfe, 0x68, 0x81, 0x43, 0xe4,
	0x8b, 0x16, 0x3c, 0x4a, 0x72, 0x53, 0x0e, 0x83, 0xc7, 0xbc, 0xf2, 0x2d, 0x54, 0x9a, 0x45, 0x9c,
	0x16, 0x89, 0x54, 0x51, 0x32, 0x9d, 0x55, 0x4c, 0xfb, 0x57, 0xf7, 0x1d, 0xe7, 0xf2, 0x56, 0x98,
	0xe4, 0x7c, 0x47, 0x8e, 0x79, 0x43, 0x08, 0xa7, 0x30, 0xa8, 0x51, 0xe9, 0xc6, 0x34, 0xa3, 0x30,
	0x6d, 0x7d, 0xf7, 0x7f, 0xc8, 0xea, 0x32, 0x69, 0xba, 0x5a, 0x07, 0xf5, 0xa0, 0x7b, 0x09, 0x4f,
	0x3f, 0x5b, 0xa3, 0xfc, 0x4b, 0x1f, 0xe9, 0xce, 0x08, 0x24, 0x8f, 0xf2, 0x01, 0x6f, 0xa3, 0x4d,
	0xa1, 0x1f, 0x10, 0x11, 0x6d, 0x7c, 0x6f, 0xbd, 0x44, 0xee, 0x2f, 0xf0, 0xe5, 0x3d, 0xfc, 0x0d,
	0xa9, 0xbe, 0xa9, 0xa7, 0xb2, 0xc7, 0x5f, 0x34, 0xbe, 0x71, 0x8d, 0xc1, 0xfb, 0x1b, 0x41, 0x97,
	0xd0, 0x98, 0x65, 0x8c, 0x36, 0x7e, 0xae, 0x53, 0xb0, 0x45, 0xc1, 0xf2, 0x68, 0xc9, 0x36, 0x2c,
	0xdf, 0x29, 0xb9, 0xfa, 0xe3, 0x47, 0x55, 0xda, 0x0b, 0x46, 0x73, 0x52, 0x47, 0xe0, 0x97, 0xd0,
	0x8b, 0x6e, 0x23, 0xb6, 0x89, 0x96, 0x1b, 0xaa, 0x06, 0xac, 0x3f, 0x76, 0x6b, 0xea, 0x2a, 0x26,
	0x3f, 0x28, 0x11, 0xe4, 0x0e, 0xec, 0xbd, 0x82, 0x5e, 0xe5, 0xc7, 0x36, 0x74, 0x83, 0xab, 0xab,
	0xc5, 0x45, 0xf0, 0xc1, 0x39, 0xc0, 0x3d, 0xe8, 0x5c, 0xbd, 0x9b, 0x9e, 0xbf, 0x71, 0x10, 0x06,
	0x38, 0x7c, 0x4d, 0xee, 0xce, 0x17, 0x93, 0xe9, 0x34, 0x24, 0x8e, 0xe5, 0x5a, 0x0e, 0xf2, 0x6e,
	0xe0, 0x61, 0xc8, 0x79, 0xca, 0x7f, 0xa2, 0x42, 0x44, 0x6b, 0x8a, 0x47, 0xd0, 0xa1, 0xd2, 0x36,
	0x1f, 0x1e, 0xfb, 0x7a, 0x8f, 0xf8, 0x3c, 0x8b, 0xfd, 0x99, 0xda, 0x40, 0x44, 0x03, 0xb0, 0x0f,
	0x6d, 0xb9, 0x74, 0x8c, 0x6a, 0x6e, 0x09, 0x2c, 0x17, 0x8e, 0x3f, 0x2f, 0x37, 0x12, 0x51, 0x38,
	0x6f, 0x09, 0xf6, 0x24, 0x59, 0x73, 0xba, 0x62, 0x34, 0xc9, 0x45, 0xa3, 0x70, 0xaf, 0xc0, 0x49,
	0x8a, 0x9c, 0xb3, 0x98, 0xa5, 0x49, 0xb4, 0x59, 0xb0, 0xe4, 0x3a, 0x35, 0x9f, 0xed, 0xf8, 0x5f,
	0xe9, 0x83, 0x64, 0x47, 0x8e, 0x6a, 0xe8, 0x49, 0x72, 0x2d, 0x57, 0xdb, 0xe3, 0x59, 0xb1, 0x94,
	0x9b, 0x69, 0x49, 0xf5, 0xb0, 0x51, 0x91, 0xa5, 0x89, 0xa0, 0xf8, 0xeb, 0x72, 0x26, 0x75, 0x5f,
	0x7b, 0x33, 0xf9, 0xe6, 0xc0, 0x4c, 0x25, 0x3e, 0x29, 0xfb, 0xb7, 0x3e, 0xd7, 0xbf, 0xc4, 0x2a,
	0xc8, 0xeb, 0x1e, 0x74, 0xb7, 0x5a, 0xb6, 0x93, 0x19, 0xb4, 0xe5, 0xb3, 0x4a, 0xd5, 0xdf, 0x87,
	0x97, 0xc1, 0xd4, 0x39, 0xc0, 0x7d, 0x80, 0xf7, 0xe1, 0xe5, 0x64, 0x1e, 0x90, 0x49, 0x30, 0x75,
	0x10, 0x3e, 0x02, 0xfb, 0x6d, 0x38, 0x3b, 0x0f, 0x8c, 0xc3, 0x92, 0x8e, 0xcb, 0xab, 0x77, 0xf3,
	0x70, 0xba, 0xf8, 0x91, 0x84, 0xa1, 0xd3, 0x92, 0x37, 0x2e, 0x82, 0x09, 0xf9, 0xa0, 0xed, 0xf6,
	0xf8, 0x2f, 0xb5, 0x8e, 0x22, 0x1e, 0xdf, 0x98, 0xf9, 0xff, 0x41, 0xae, 0x0c, 0x69, 0xe3, 0x7b,
	0x17, 0x91, 0xdb, 0xfc, 0x85, 0xf1, 0x1c, 0x8e, 0x3e, 0x55, 0x47, 0xfc, 0x47, 0x9e, 0xe7, 0x77,
	0xd1, 0x46, 0x55, 0x47, 0xe8, 0x5b, 0xb4, 0x3c, 0x54, 0x4f, 0x72, 0xf6, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x75, 0xa9, 0x58, 0xc4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchOrdersClient is the client API for SearchOrders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchOrdersClient interface {
	// Defining rpc for unary operations
	// We can reference a nested message using the notation parent.message
	Search(ctx context.Context, in *ServerOrders_Server, opts ...grpc.CallOption) (*ServerOrders, error)
	// Defining streaming RPCs can be done by appending the keyword stream to a message type
	SubscribeOrders(ctx context.Context, opts ...grpc.CallOption) (SearchOrders_SubscribeOrdersClient, error)
}

type searchOrdersClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchOrdersClient(cc grpc.ClientConnInterface) SearchOrdersClient {
	return &searchOrdersClient{cc}
}

func (c *searchOrdersClient) Search(ctx context.Context, in *ServerOrders_Server, opts ...grpc.CallOption) (*ServerOrders, error) {
	out := new(ServerOrders)
	err := c.cc.Invoke(ctx, "/example.SearchOrders/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchOrdersClient) SubscribeOrders(ctx context.Context, opts ...grpc.CallOption) (SearchOrders_SubscribeOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SearchOrders_serviceDesc.Streams[0], "/example.SearchOrders/SubscribeOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchOrdersSubscribeOrdersClient{stream}
	return x, nil
}

type SearchOrders_SubscribeOrdersClient interface {
	Send(*ServerOrders_Server) error
	Recv() (*SubscribeOrderResponse, error)
	grpc.ClientStream
}

type searchOrdersSubscribeOrdersClient struct {
	grpc.ClientStream
}

func (x *searchOrdersSubscribeOrdersClient) Send(m *ServerOrders_Server) error {
	return x.ClientStream.SendMsg(m)
}

func (x *searchOrdersSubscribeOrdersClient) Recv() (*SubscribeOrderResponse, error) {
	m := new(SubscribeOrderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchOrdersServer is the server API for SearchOrders service.
type SearchOrdersServer interface {
	// Defining rpc for unary operations
	// We can reference a nested message using the notation parent.message
	Search(context.Context, *ServerOrders_Server) (*ServerOrders, error)
	// Defining streaming RPCs can be done by appending the keyword stream to a message type
	SubscribeOrders(SearchOrders_SubscribeOrdersServer) error
}

// UnimplementedSearchOrdersServer can be embedded to have forward compatible implementations.
type UnimplementedSearchOrdersServer struct {
}

func (*UnimplementedSearchOrdersServer) Search(ctx context.Context, req *ServerOrders_Server) (*ServerOrders, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedSearchOrdersServer) SubscribeOrders(srv SearchOrders_SubscribeOrdersServer) error {
	return status1.Errorf(codes.Unimplemented, "method SubscribeOrders not implemented")
}

func RegisterSearchOrdersServer(s *grpc.Server, srv SearchOrdersServer) {
	s.RegisterService(&_SearchOrders_serviceDesc, srv)
}

func _SearchOrders_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOrders_Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchOrdersServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.SearchOrders/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchOrdersServer).Search(ctx, req.(*ServerOrders_Server))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchOrders_SubscribeOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SearchOrdersServer).SubscribeOrders(&searchOrdersSubscribeOrdersServer{stream})
}

type SearchOrders_SubscribeOrdersServer interface {
	Send(*SubscribeOrderResponse) error
	Recv() (*ServerOrders_Server, error)
	grpc.ServerStream
}

type searchOrdersSubscribeOrdersServer struct {
	grpc.ServerStream
}

func (x *searchOrdersSubscribeOrdersServer) Send(m *SubscribeOrderResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *searchOrdersSubscribeOrdersServer) Recv() (*ServerOrders_Server, error) {
	m := new(ServerOrders_Server)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SearchOrders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.SearchOrders",
	HandlerType: (*SearchOrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchOrders_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOrders",
			Handler:       _SearchOrders_SubscribeOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}
