// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/PacktPublishing/Building-Microservices-with-Go-Second-Edition/product-api/9_docs/client-sdk/models"
)

// CreateReader is a Reader for the Create structure.
type CreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewCreateNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateOK creates a CreateOK with default headers values
func NewCreateOK() *CreateOK {
	return &CreateOK{}
}

/*CreateOK handles this case with default header values.

Data structure representing a single product
*/
type CreateOK struct {
	Payload *models.Product
}

func (o *CreateOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] createOK  %+v", 200, o.Payload)
}

func (o *CreateOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *CreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUnprocessableEntity creates a CreateUnprocessableEntity with default headers values
func NewCreateUnprocessableEntity() *CreateUnprocessableEntity {
	return &CreateUnprocessableEntity{}
}

/*CreateUnprocessableEntity handles this case with default header values.

Validation errors defined as an array of strings
*/
type CreateUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *CreateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /products][%d] createUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNotImplemented creates a CreateNotImplemented with default headers values
func NewCreateNotImplemented() *CreateNotImplemented {
	return &CreateNotImplemented{}
}

/*CreateNotImplemented handles this case with default header values.

Generic error message returned as a string
*/
type CreateNotImplemented struct {
	Payload *models.GenericError
}

func (o *CreateNotImplemented) Error() string {
	return fmt.Sprintf("[POST /products][%d] createNotImplemented  %+v", 501, o.Payload)
}

func (o *CreateNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
