// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSingleParams creates a new ListSingleParams object
// with the default values initialized.
func NewListSingleParams() *ListSingleParams {
	var ()
	return &ListSingleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListSingleParamsWithTimeout creates a new ListSingleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSingleParamsWithTimeout(timeout time.Duration) *ListSingleParams {
	var ()
	return &ListSingleParams{

		timeout: timeout,
	}
}

// NewListSingleParamsWithContext creates a new ListSingleParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSingleParamsWithContext(ctx context.Context) *ListSingleParams {
	var ()
	return &ListSingleParams{

		Context: ctx,
	}
}

// NewListSingleParamsWithHTTPClient creates a new ListSingleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListSingleParamsWithHTTPClient(client *http.Client) *ListSingleParams {
	var ()
	return &ListSingleParams{
		HTTPClient: client,
	}
}

/*ListSingleParams contains all the parameters to send to the API endpoint
for the list single operation typically these are written to a http.Request
*/
type ListSingleParams struct {

	/*ID
	  The id of the product for which the operation relates

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list single params
func (o *ListSingleParams) WithTimeout(timeout time.Duration) *ListSingleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list single params
func (o *ListSingleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list single params
func (o *ListSingleParams) WithContext(ctx context.Context) *ListSingleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list single params
func (o *ListSingleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list single params
func (o *ListSingleParams) WithHTTPClient(client *http.Client) *ListSingleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list single params
func (o *ListSingleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list single params
func (o *ListSingleParams) WithID(id int64) *ListSingleParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list single params
func (o *ListSingleParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListSingleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
