// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/PacktPublishing/Building-Microservices-with-Go-Second-Edition/product-api/9_docs/client-sdk/models"
)

// UpdateReader is a Reader for the Update structure.
type UpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateCreated creates a UpdateCreated with default headers values
func NewUpdateCreated() *UpdateCreated {
	return &UpdateCreated{}
}

/*UpdateCreated handles this case with default header values.

No content is returned by this API endpoint
*/
type UpdateCreated struct {
}

func (o *UpdateCreated) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateCreated ", 201)
}

func (o *UpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateNotFound creates a UpdateNotFound with default headers values
func NewUpdateNotFound() *UpdateNotFound {
	return &UpdateNotFound{}
}

/*UpdateNotFound handles this case with default header values.

Generic error message returned as a string
*/
type UpdateNotFound struct {
	Payload *models.GenericError
}

func (o *UpdateNotFound) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateNotFound  %+v", 404, o.Payload)
}

func (o *UpdateNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateUnprocessableEntity creates a UpdateUnprocessableEntity with default headers values
func NewUpdateUnprocessableEntity() *UpdateUnprocessableEntity {
	return &UpdateUnprocessableEntity{}
}

/*UpdateUnprocessableEntity handles this case with default header values.

Validation errors defined as an array of strings
*/
type UpdateUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /products][%d] updateUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
