# Use golang as the build container
FROM golang:1.14.6-alpine as build

RUN apk update && apk add --no-cache git

# Copy the source code into the working directory
COPY . /go/src/github.com/PacktPublishing/Building-Microservices-with-Go-Second-Edition

# Set the working directory
WORKDIR /go/src/github.com/PacktPublishing/Building-Microservices-with-Go-Second-Edition/product-images

# Build the application
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
      -ldflags='-w -s -extldflags "-static"' -a \
      -o /bin/product-images .

# Use scratch as the run container
FROM scratch

# Copy the statically linked binary
COPY --from=build /bin/product-images /bin/product-images

EXPOSE 9091

ENTRYPOINT [ "/bin/product-images"]